version: 0.1.0

project: example-procedural-world
jobs:
  nav_tests: # Overall job name
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile 
    runtime:
      simulator: gazebo:fortress
      framework: ros2:0
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          map: map
        output_path: /tmp/artefacts_output
        params:
          test/seed: [1,2,3]
          test/max_tree_density: [4.0, 0.2]
      settings:
        - name: reach_goal_1
          ros_testfile: "src/nav_test/test/test_navigation.launch.py"