version: 0.1.0

project: example-procedural-world
jobs:
  nav_tests: # Overall job name
    type: test
    package:
      docker:
        build:
          dockerfile: ./Dockerfile 
      custom:
        commands:
          - apt install ffmpeg
          - apt install python3-transforms3d
          - wget https://mirror.clarkson.edu/blender/release/Blender3.4/blender-3.4.1-linux-x64.tar.xz
          - tar -xvf blender-3.4.1-linux-x64.tar.xz --strip-components=1 -C /bin
          - rm -rf blender-3.4.1-linux-x64.tar.xz
          - rm -rf blender-3.4.1-linux-x64
    runtime:
      simulator: gazebo:fortress
      framework: ros2:0
    timeout: 5 #minutes
    scenarios:
      defaults: # Global to all scenarios, and overriden in specific scenarios.
        subscriptions:
          map: map
        output_path: /tmp/artefacts_output
        params:
          test/seed: [1,2,3]
      settings:
        - name: reach_goal_1
          ros_testfile: "src/nav_test/test/test_navigation.launch.py"